name: dc2020
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=19.3.0
  - backcall=0.1.0
  - bleach=3.1.0
  - bokeh=1.4.0
  - boost-cpp=1.70.0
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - cairo=1.16.0
  - cartopy=0.17.0
  - certifi=2019.11.28
  - cffi=1.13.2
  - cfitsio=3.470
  - cftime=1.0.4.2
  - chardet=3.0.4
  - click=7.0
  - click-plugins=1.1.1
  - cligj=0.5.0
  - cloudpickle=1.2.2
  - cryptography=2.8
  - ctd=1.0.0
  - curl=7.68.0
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask=2.10.1
  - dask-core=2.10.1
  - dbus=1.13.6
  - decorator=4.4.1
  - defusedxml=0.6.0
  - distributed=2.10.0
  - entrypoints=0.3
  - expat=2.2.9
  - fiona=1.8.9.post2
  - fontconfig=2.13.1
  - freetype=2.10.0
  - freexl=1.0.5
  - fsspec=0.6.2
  - gdal=3.0.1
  - geopandas=0.6.3
  - geos=3.7.2
  - geotiff=1.5.1
  - gettext=0.19.8.1
  - giflib=5.1.7
  - glib=2.58.3
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - gsw=3.3.1
  - hdf4=4.2.13
  - hdf5=1.10.5
  - heapdict=1.0.1
  - icu=64.2
  - idna=2.8
  - importlib_metadata=1.5.0
  - ipykernel=5.1.4
  - ipython=7.12.0
  - ipython_genutils=0.2.0
  - jedi=0.16.0
  - jinja2=2.11.1
  - jpeg=9c
  - json-c=0.13.1
  - json5=0.9.0
  - jsonschema=3.2.0
  - jupyter_client=5.3.4
  - jupyter_core=4.6.2
  - jupyterlab=1.2.6
  - jupyterlab_server=1.0.6
  - kealib=1.4.10
  - kiwisolver=1.1.0
  - krb5=1.16.4
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libcurl=7.68.0
  - libdap4=3.20.4
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgdal=3.0.1
  - libgfortran-ng=7.3.0
  - libgomp=9.2.0
  - libiconv=1.15
  - libkml=1.3.0
  - liblapack=3.8.0
  - libllvm8=8.0.1
  - libllvm9=9.0.1
  - libnetcdf=4.6.2
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libpq=11.5
  - libsodium=1.0.17
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.8.2
  - libstdcxx-ng=9.2.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxkbcommon=0.10.0
  - libxml2=2.9.10
  - llvmlite=0.31.0
  - locket=0.2.0
  - lz4-c=1.8.3
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mistune=0.8.4
  - msgpack-python=0.6.2
  - munch=2.5.0
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ncurses=6.1
  - netcdf4=1.5.1.2
  - notebook=6.0.3
  - nspr=4.25
  - nss=3.47
  - numba=0.48.0
  - numpy=1.18.1
  - oceans=0.8.0
  - olefile=0.46
  - openjpeg=2.3.1
  - openssl=1.1.1d
  - owslib=0.19.1
  - packaging=20.1
  - pandas=0.25.3
  - pandas-flavor=0.2.0
  - pandoc=2.9.1.1
  - pandocfilters=1.4.2
  - parso=0.6.1
  - partd=1.1.0
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=20.0.2
  - pixman=0.38.0
  - poppler=0.67.0
  - poppler-data=0.4.9
  - postgresql=11.5
  - proj4=6.1.1
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.3
  - psutil=5.6.7
  - psycopg2=2.8.4
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pyepsg=0.4.0
  - pygc=1.2.1
  - pygments=2.5.2
  - pykdtree=1.3.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyproj=2.3.1
  - pyqt=5.12.3
  - pyrsistent=0.15.7
  - pyshp=2.1.0
  - pysocks=1.7.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pyyaml=5.3
  - pyzmq=18.1.1
  - qt=5.12.5
  - readline=8.0
  - requests=2.22.0
  - rtree=0.9.4
  - scipy=1.4.1
  - seawater=3.3.4
  - send2trash=1.5.0
  - setuptools=45.2.0
  - shapely=1.6.4
  - simplejson=3.17.0
  - six=1.14.0
  - sortedcontainers=2.1.0
  - sqlite=3.30.1
  - tbb=2018.0.5
  - tblib=1.6.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tiledb=1.6.2
  - tk=8.6.10
  - toolz=0.10.0
  - tornado=6.0.3
  - traitlets=4.3.3
  - tzcode=2019a
  - urllib3=1.25.7
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - wheel=0.34.2
  - xarray=0.15.0
  - xerces-c=3.2.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.2.2
  - zeromq=4.3.2
  - zict=1.0.0
  - zipp=2.2.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - git+https://github.com/kwilcox/codar_processing.git@qc-cleanup#egg=codar_processing
