name: dc2020
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.17.0
  - geopandas=0.6.3
  - jupyterlab=1.2.6
  - matplotlib=3.1.3
  - netcdf4=1.5.1.2
  - numpy=1.18.1
  - oceans=0.8.0
  - pandas=0.25.3
  - python=3.7.6
  - scipy=1.4.1
  - seawater=3.3.4
  - xarray=0.15.0
  - pip
  - numba
  - pip:
    - git+https://github.com/kwilcox/codar_processing.git@qc-cleanup#egg=codar_processing
