# Exploring a Radial RUV file

In [1]:
import os
from codar_processing.src.radials import Radial

In [2]:
radial_file = 'data/radials/CORE/ideal/2018/201801/20180101/RDL_i_UNC_CORE_2018_01_01_0000.hfrss10lluv'

In [3]:
r = Radial(radial_file)

## Export to new file format
* export - Export the Radial instance as either a new .ruv file ~~or .netcdf~~

## Radial File Information
* full_file - String of the absolute path to the file
* file_path - String of the file path excluding the filename
* file_name - String of the filename
* file_type - String of the filetype

In [4]:
r.full_file

'/data/dev/data_challenge_2020/data/radials/CORE/ideal/2018/201801/20180101/RDL_i_UNC_CORE_2018_01_01_0000.hfrss10lluv'

In [5]:
r.file_name

'RDL_i_UNC_CORE_2018_01_01_0000.hfrss10lluv'

In [6]:
r.file_path

'data/radials/CORE/ideal/2018/201801/20180101'

In [7]:
r.file_type()

'radial'

## Radial Metadata File
* metadata - Dictionary of header information

We can view the header and footer information in a dictionary format by doing the following:

In [8]:
r.metadata

OrderedDict([('CTF', '1.00'),
             ('FileType', 'LLUV rdls "RadialMap"'),
             ('LLUVSpec', '1.18  2012 05 07'),
             ('UUID', '07C1C676-6C02-4E1F-8735-C851E98F27F5'),
             ('Manufacturer', 'CODAR Ocean Sensors. SeaSonde'),
             ('Site', 'CORE ""'),
             ('TimeStamp', '2018 01 01  00 00 00'),
             ('TimeZone', '"UTC" +0.000 0 "GMT"'),
             ('TimeCoverage', '180.000 Minutes'),
             ('Origin', '34.7600833  -76.4113667'),
             ('GreatCircle', '"WGS84" 6378137.000  298.257223562997'),
             ('GeodVersion', '"CGEO" 1.57  2009 03 10'),
             ('LLUVTrustData', 'all  all lluv xyuv rbvd'),
             ('RangeStart', '1'),
             ('RangeEnd', '40'),
             ('RangeResolutionKMeters', '5.824900'),
             ('AntennaBearing', '178.0 True'),
             ('ReferenceBearing', '0 True'),
             ('AngularResolution', '5 Deg'),
             ('SpatialResolution', '5 Deg'),
             ('P

In [9]:
r.metadata['TimeStamp']

'2018 01 01  00 00 00'

Next, we can clean up the header dictionary. `clean_header` is specifically coded to clean the header data into known variable types and formats. `clean_header` is a destrictive method and does not return anything. It changes the `metadata` attribute in place. Because of this, you should only run it against a `Radial` object once.

In [10]:
r.clean_header()

In [11]:
r.metadata

OrderedDict([('CTF', 1.0),
             ('FileType', 'LLUV rdls "RadialMap"'),
             ('LLUVSpec', '1.18  2012 05 07'),
             ('UUID', '07C1C676-6C02-4E1F-8735-C851E98F27F5'),
             ('Manufacturer', 'CODAR Ocean Sensors. SeaSonde'),
             ('Site', 'CORE'),
             ('TimeStamp', datetime.datetime(2018, 1, 1, 0, 0)),
             ('TimeZone', 'UTC'),
             ('TimeCoverage', 180),
             ('Origin', '34.7600833  -76.4113667'),
             ('GreatCircle', '"WGS84" 6378137.000  298.257223562997'),
             ('GeodVersion', '"CGEO" 1.57  2009 03 10'),
             ('LLUVTrustData', 'all  all lluv xyuv rbvd'),
             ('RangeStart', 1),
             ('RangeEnd', 40),
             ('RangeResolutionKMeters', 5.8249),
             ('AntennaBearing', 178),
             ('ReferenceBearing', 0),
             ('AngularResolution', 5),
             ('SpatialResolution', 5),
             ('PatternType', 'Ideal'),
             ('PatternDate', datetime

In [12]:
r.metadata['TimeStamp']

datetime.datetime(2018, 1, 1, 0, 0)

## Radial Table Data (Pandas Dataframe)
* data - Dataframe of radial data
* diagnostics_radial - Dataframe of radial diagnostic data
* diagnostics_hardware - Dataframe of radial hardware data

Dataframes will start with an index automatically generated by Pandas when the data is loaded into the dataframe.

In [13]:
r.data

LOND       LATD    VELU     VELV  VFLG    ESPC    ETMP     MAXV     MINV  ERSC  ERTC      XDST      YDST      RNGE   BEAR     VELO   HEAD  SPRC
0    -76.397046  34.811243  -1.272   -5.504   128     NaN   2.319    5.650    5.649     1     2    1.3103    5.6756    5.8249   13.0    5.649  193.0     1
1    -76.381481  34.806440   3.461    6.504   128     NaN   7.264   -7.367   -7.367     1     2    2.7346    5.1431    5.8249   28.0   -7.367  208.0     1
2    -76.364066  34.795208  -3.677   -3.308   128     NaN  17.972    4.946    4.946     1     3    4.3287    3.8976    5.8249   48.0    4.946  228.0     1
3    -76.357394  34.787896   7.531    4.701     0  26.635  12.209   17.757   -8.879     2     2    4.9398    3.0867    5.8249   58.0   -8.878  238.0     1
4    -76.354662  34.783908 -21.819  -11.102     0   4.931   0.944   31.375   -1.717     5     4    5.1900    2.6444    5.8249   63.0   24.481  243.0     1
...         ...        ...     ...      ...   ...     ...     ...      ...      ...   ...   ...       ...       ...       ...    ...      ...    ...   ...
2095 -78.575501  35.884721 -26.783   16.573   128   5.762  23.946    9.789  -38.639     5     4 -195.4069  126.8987  232.9960  303.0  -31.496  121.7    40
2096 -78.448604  36.036047  -4.656    3.486   128  26.492  45.223   43.688  -32.182     6     3 -183.6034  143.4467  232.9960  308.0   -5.816  126.8    40
2097 -78.305471  36.177649  31.766  -28.503   128  46.211  66.790  106.645  -11.197     3     2 -170.4025  158.9029  232.9960  313.0   42.679  131.9    40
2098 -77.974867  36.427233  85.114 -109.294   128   1.212  92.417  140.544  138.122     2     2 -140.2205  186.0789  232.9960  323.0  138.526  142.1    40
2099 -77.387980  36.703222   9.643  -23.200   128     NaN  23.407   25.124   25.124     1     2  -87.2818  216.0301  232.9960  338.0   25.124  157.4    40

[2100 rows x 18 columns]

In [14]:
r.diagnostics_hardware

TIME  RTMP  MTMP  XTRP     RUNT  SP24  SP05  SN05   SP12  XPHT  ...  EXTA  EXTB     CRUN  TYRS  TMON  TDAY  THRS  TMIN  TSEC            datetime
0    -90    28    40     0  5929876  23.7  4.95 -4.98  12.09    30  ...     0     0  1350.89  2017    12    31    22    30     0 2017-12-31 22:30:00
1    -75    28    40     0  5930833  23.7  4.93 -4.98  12.09    30  ...     0     0  1366.53  2017    12    31    22    45     0 2017-12-31 22:45:00
2    -60    27    40     0  5931670  23.7  4.95 -4.98  12.09    29  ...     0     0  1381.42  2017    12    31    23     0     0 2017-12-31 23:00:00
3    -45    27    40     0  5932626  23.7  4.95 -4.98  12.09    29  ...     0     0  1396.53  2017    12    31    23    15     0 2017-12-31 23:15:00
4    -30    27    40     0  5933465  23.7  4.95 -4.98  12.09    29  ...     0     0  1410.74  2017    12    31    23    30     0 2017-12-31 23:30:00
5    -15    27    40     0  5934422  23.6  4.95 -4.98  12.09    29  ...     0     0  1426.59  2017    12    31    23    45     0 2017-12-31 23:45:00
6      0    26    39     0  5935312  23.7  4.95 -4.98  12.16    28  ...     0     0     1.48  2018     1     1     0     0     0 2018-01-01 00:00:00
7     15    27    39     0  5936139  23.6  4.95 -4.98  12.09    29  ...     0     0    16.16  2018     1     1     0    15     0 2018-01-01 00:15:00
8     30    27    39     0  5937098  23.6  4.93 -4.98  12.09    29  ...     0     0    31.39  2018     1     1     0    30     0 2018-01-01 00:30:00
9     45    26    39     0  5937935  23.6  4.95 -4.98  12.09    28  ...     0     0    46.01  2018     1     1     0    45     0 2018-01-01 00:45:00
10    60    26    39     0  5938900  23.4  4.95 -4.98  12.09    28  ...     0     0    61.57  2018     1     1     1     0     0 2018-01-01 01:00:00
11    75    26    39     0  5939734  23.4  4.95 -4.98  12.09    28  ...     0     0    76.40  2018     1     1     1    15     0 2018-01-01 01:15:00
12    90    26    39     0  5940692  23.4  4.95 -4.98  12.09    28  ...     0     0    91.56  2018     1     1     1    30     0 2018-01-01 01:30:00

[13 rows x 33 columns]

In [15]:
r.diagnostics_radial

TIME   AMP1   AMP2   PH13   PH23   CPH1   CPH2   SNF1   SNF2   SNF3  ...   RABA  RTYP  STYP  TYRS  TMON  TDAY  THRS  TMIN  TSEC            datetime
0 -5400  0.672  0.705 -113.5 -107.4 -120.0 -105.0 -146.0 -145.0 -151.0  ...  132.6     1    68  2017    12    31    22    30     0 2017-12-31 22:30:00
1 -3600  0.665  0.700 -114.1 -107.4 -120.0 -105.0 -147.0 -146.0 -151.0  ...  129.1     1    68  2017    12    31    23     0     0 2017-12-31 23:00:00
2 -1800  0.714  0.687 -112.9 -105.8 -120.0 -105.0 -147.0 -145.0 -150.0  ...  130.7     1    68  2017    12    31    23    30     0 2017-12-31 23:30:00
3     0  0.681  0.708 -113.6 -105.2 -120.0 -105.0 -147.0 -146.0 -148.0  ...  131.7     1    68  2018     1     1     0     0     0 2018-01-01 00:00:00
4     0  0.681  0.708 -113.6 -105.2 -120.0 -105.0 -147.0 -146.0 -148.0  ...  129.6     5    68  2018     1     1     0     0     0 2018-01-01 00:00:00
5  1800  0.690  0.690 -113.8 -105.6 -120.0 -105.0 -146.0 -145.0 -148.0  ...  133.0     1    68  2018     1     1     0    30     0 2018-01-01 00:30:00
6  3600  0.696  0.708 -113.4 -105.4 -120.0 -105.0 -145.0 -145.0 -148.0  ...  133.0     1    68  2018     1     1     1     0     0 2018-01-01 01:00:00

[7 rows x 32 columns]

## Quality Control tests

Six QARTOD radial tests have been implemented directly into `codar_processing`. More will be added in time.

* qc_qartod_avg_radial_bearing
* qc_qartod_valid_location
* qc_qartod_radial_count
* qc_qartod_maximum_velocity
* qc_qartod_spatial_median
* qc_qartod_syntax

## Syntax

**Description:** A collection of tests ensuring proper formatting and existence of fields within a radial file.

**Test specifications:** Acceptable files types, site codes, coordinates, APM names, etc., must be presented. For example, the national network performs the following suite of tests:
* All radial files acquired by HFRNet portals report the data timestamp in the filename.
The filename timestamp must not be any more than 72 hours in the future relative to the
portals’ system time.
* The file name timestamp must match the timestamp reported within the file.
* Radial data tables (Lon, Lat, U, V, ...) must not be empty.
* Radial data table columns stated must match the number of columns reported for each
row (a useful test for catching partial or corrupted files).
* The site location must be within range: − 180 ≤ Longitude ≤ 180 − 90 ≤ Latitude ≤ 90.
* As a minimum, the following metadata must be defined:
    * File type (LLUV)
    * Site code
    * Timestamp
    * Site coordinates
    * Antenna pattern type (measured or idealized)
    * Time zone (only Coordinated Universal Time or Greenwich Mean Time accepted)

If a radial file is successfully loaded by the Radial class that file automatically passes the QARTOD Syntax test. 

In [16]:
r.initialize_qc()
r.qc_qartod_syntax()
r.metadata['QCTest']

['qc_qartod_syntax (QC06) [N/A]: 1']

## Valid Location 
Removes radial vectors placed over land or in other unmeasureable areas.

**Description:** Radial vector coordinates are checked against a reference file containing information about which locations
are over land or in an unmeasurable area (for example, behind an island or point of land). Radials in these
areas will be flagged with a code (FLOC) in the radial file (+128 in CODAR radial files) and are not included in
total vector calculations.

**Test Specifications:**
For CODAR systems, the reference file is called AngSeg_XXXX.txt, where XXXX is the four-letter site code of the station and is located in the “RadialConfigs” folder. These vectors receive a code of +128 in the flag column of the radial text file. BF systems use pre-set grid locations for radials.

**Default Location Flag:** 128 (corresponds to CODAR AngSeg flag)

Flags (VLOC): 
* Fail = 4
    * Radial contains a user-defined location flag code in the radial file
* Pass = 1
    * Radial does not contain a user-defined location flag code in the radial file.

In [17]:
r.qc_qartod_valid_location()
r.data[['LOND', 'LATD', 'QC08']]

LOND       LATD  QC08
0    -76.397046  34.811243     4
1    -76.381481  34.806440     4
2    -76.364066  34.795208     4
3    -76.357394  34.787896     1
4    -76.354662  34.783908     1
...         ...        ...   ...
2095 -78.575501  35.884721     4
2096 -78.448604  36.036047     4
2097 -78.305471  36.177649     4
2098 -77.974867  36.427233     4
2099 -77.387980  36.703222     4

[2100 rows x 3 columns]

## Max Threshold
Ensures that a radial currend speed is not unrealistically high.

**Description:** The maximum radial speed threshold (RSPDMAX) represents the maximum reasonable surface radial
velocity for the given domain.

**Test Specifications:** The maximum total speed threshold is 1 m/s for the West
Coast of the United States and 3 m/s for the East/Gulf Coast domain. The threshold must vary by region. For
example, the presence of the Gulf Stream dictates the higher threshold on the East Coast.

**Default Max Threshold:** 250 cm/s

Flags (VLOC): 
* Fail = 4
    * Radial current speed exceeds the maximum radial speed threshold
* Pass = 1
    * Radial current speed is less than or equal to the maximum radial speed threshold.

In [18]:
r.qc_qartod_maximum_velocity(radial_max_speed=250, radial_high_speed=150)  # cm/s
r.data[['LOND', 'LATD', 'VELU', 'VELV', 'QC07']]

LOND       LATD    VELU     VELV  QC07
0    -76.397046  34.811243  -1.272   -5.504     1
1    -76.381481  34.806440   3.461    6.504     1
2    -76.364066  34.795208  -3.677   -3.308     1
3    -76.357394  34.787896   7.531    4.701     1
4    -76.354662  34.783908 -21.819  -11.102     1
...         ...        ...     ...      ...   ...
2095 -78.575501  35.884721 -26.783   16.573     1
2096 -78.448604  36.036047  -4.656    3.486     1
2097 -78.305471  36.177649  31.766  -28.503     1
2098 -77.974867  36.427233  85.114 -109.294     1
2099 -77.387980  36.703222   9.643  -23.200     1

[2100 rows x 5 columns]

## Radial Count
Rejects radials in files with low radial counts (poor radial map coverage)

**Description:** The number of radials (RCNT) in a radial file must be above a threshold value RCNT_MIN to pass the test and above a value RC_LOW to not be considered suspect. If the number of radials is below the minimum level, it indicates a problem with data collection. In this case, the file should be rejected and none of the radials used for total vector processing.

**Test Specifications:** The RC_LOW threshold may be based on the national
network performance metric threshold value of 300. The choice of 300 radial solutions came from grouping
radial files over a certain time period from all stations, looking at the cumulative density function for counts,
and selecting a value around 10%. However, this threshold does not work for all stations. A custom value for
a site might be found by following the same procedure for the individual station.

**Default Max Threshold:** min_radials = 150; low_radials = 300 

Flags (VLOC): 
* Fail = 4
    * Number of radials is less than min_radials
* Suspect = 3
    * Number of radials is greater than min_radials but less than or equal to low_radials
* Pass = 1
    * Number of radials is greater than low_radials.
    
This will not add an extra column to the file. Rather it will add the test result a new key, qc_qartod_radial_count, to the header file of a newly exported radial.

In [19]:
r.qc_qartod_radial_count(radial_min_count=140, radial_low_count=50)
r.data[['LOND', 'LATD', 'VFLG', 'QC09']]

LOND       LATD  VFLG  QC09
0    -76.397046  34.811243   128     1
1    -76.381481  34.806440   128     1
2    -76.364066  34.795208   128     1
3    -76.357394  34.787896     0     1
4    -76.354662  34.783908     0     1
...         ...        ...   ...   ...
2095 -78.575501  35.884721   128     1
2096 -78.448604  36.036047   128     1
2097 -78.305471  36.177649   128     1
2098 -77.974867  36.427233   128     1
2099 -77.387980  36.703222   128     1

[2100 rows x 4 columns]